services:
  api:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-prod
    env_file: [.env.prod]
    expose: ["3000"]
    networks: [app-net]
    restart: unless-stopped

  api-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-test
    env_file: [.env.dev]
    expose: ["3000"] # también detrás de nginx
    networks: [app-net]
    restart: unless-stopped
