# docker compose --profile prod up -d --build
# docker compose --profile dev up -d --build
# verificacion - logs:
# docker compose --profile prod logs -f api

services:
  api:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-prod
    env_file:
      - .env.prod
    # Exponemos sólo dentro de la red docker (Nginx lo ve). No usamos ports:
    expose:
      - "5111"
    networks:
      - appnet
    restart: unless-stopped

  api-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-test
    env_file:
      - .env.dev
    expose:
      - "5111"
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    external: true
